config/routes.rb
BillOfMaterialx::Engine.routes.draw do
  
  resources :boms do
    collection do
      get :search
      get :search_results
      #get :stats
      #get :stats_results 
    end
  end
  root :to => 'boms#index'
end

app/models/bill_of_materialx/bom.rb
module BillOfMaterialx
  class Bom < ActiveRecord::Base
    attr_accessor :project_id_noupdate, :supplier_name, :manufacturer_name, :status_name, :id_noupdate, :wf_comment, :customer_name, :project_name
    attr_accessible :actual_receiving_date, :brief_note, :last_updated_by_id, :manufacturer_id, :name, :order_date, :part_num, :project_id, :qty, :received,
                    :receiving_date, :spec, :status_id, :supplier_id, :unit, :void, :wf_state, :wfid, :customer_name, :project_name,
                    :as => :role_new
    attr_accessible :actual_receiving_date, :brief_note, :last_updated_by_id, :manufacturer_id, :name, :order_date, :part_num, :qty, :received,
                    :receiving_date, :spec, :status_id, :supplier_id, :unit, :void, :wf_state, :wfid,
                    :project_id_noupdate, :supplier_name, :manufacturer_name, :status_name, :customer_name, :project_name,
                    :as => :role_update
    
    belongs_to :project, :class_name => BillOfMaterialx.project_class.to_s
    belongs_to :supplier, :class_name => BillOfMaterialx.supplier_class.to_s
    belongs_to :status, :class_name => 'Commonx::MiscDefinition'
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :manufacturer, :class_name => BillOfMaterialx.manufacturer_class
    
    validates_presence_of :name, :spec, :unit 
    validates :project_id, :qty, :presence => true,
                                 :numericality => {:greater_than => 0, :only_integer => true}
    validates :name, :uniqueness => {:scope => [:project_id, :manufacturer_id], :case_sensitive => false, :message => I18n.t('No duplicate name')}
    
    
  end
end

app/controllers/bill_of_materialx/application_controller.rb
module BillOfMaterialx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/bill_of_materialx/boms_controller.rb
require_dependency "bill_of_materialx/application_controller"

module BillOfMaterialx
  class BomsController < ApplicationController
    before_action :require_employee
    before_action :load_parent_record
        
    def index
      @title = t('BOMs')
      @boms = params[:bill_of_materialx_boms][:model_ar_r]  #returned by check_access_right
      @boms = @boms.where(:project_id => BillOfMaterialx.project_class.where(:customer_id => @customer.id).pluck('id')) if @customer
      @boms = @boms.where(:project_id => @project.id) if @project       
      @boms = @boms.page(params[:page]).per_page(@max_pagination) 
      @erb_code = find_config_const('bom_index_view', 'bill_of_materialx')
    end
  
    def new
      @title = t('New BOM')
      @bom = BillOfMaterialx::Bom.new()
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('bom_new_view', 'bill_of_materialx')
    end
  
    def create
      @bom = BillOfMaterialx::Bom.new(params[:bom], :as => :role_new)
      @bom.last_updated_by_id = session[:user_id]
      if @bom.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @project = BillOfMaterialx.project_class.find_by_id(params[:bom][:project_id]) if params[:bom].present? && params[:bom][:project_id].present?
        @customer = BillOfMaterialx.customer_class.find_by_id(@project.customer_id) if params[:bom].present? && params[:bom][:project_id].present?
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        @erb_code = find_config_const('bom_new_view', 'bill_of_materialx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update BOM')
      @bom = BillOfMaterialx::Bom.find_by_id(params[:id])
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('bom_edit_view', 'bill_of_materialx')
      #if @bom.wf_state.present? && @bom.current_state != :initial_state
       # redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=NO Update. Record Being Processed!")
      #end
    end
  
    def update
      @bom = BillOfMaterialx::Bom.find_by_id(params[:id])
      @bom.last_updated_by_id = session[:user_id]
      if @bom.update_attributes(params[:bom], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        @erb_code = find_config_const('bom_edit_view', 'bill_of_materialx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('BOM Info')
      @bom = BillOfMaterialx::Bom.find_by_id(params[:id])
      @erb_code = find_config_const('bom_show_view', 'bill_of_materialx')
    end
    
    protected
    def load_parent_record
      @customer = BillOfMaterialx.customer_class.find_by_id(params[:customer_id]) if params[:customer_id].present?
      @project = BillOfMaterialx.project_class.find_by_id(params[:project_id]) if params[:project_id].present?
      @customer = BillOfMaterialx.customer_class.find_by_id(@project.customer_id) if params[:project_id].present?
      @project = BillOfMaterialx.project_class.find_by_id(BillOfMaterialx::Bom.find_by_id(params[:id]).project_id) if params[:id].present?
      @customer = BillOfMaterialx.customer_class.find_by_id(@project.customer_id) if params[:id].present?
    end
    
  end
end

app/helpers/bill_of_materialx/application_helper.rb
module BillOfMaterialx
  module ApplicationHelper
  end
end

app/helpers/bill_of_materialx/boms_helper.rb
module BillOfMaterialx
  module BomsHelper
  end
end

app/views/bill_of_materialx/boms/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
  <h4><%=@title %></h4>

<%= simple_form_for @bom do |f| %> 

  <%= f.input :customer_name, :label => t('Customer'), :readonly => true, :input_html => {:value => @customer.name} %>
  <%= f.input :project_name, :label => t('Project Name'), :readonly => true, :input_html => {:value => @project.name} %>
  <%= f.input :name, :label => t('Part Name'), :readonly => readonly?(@bom, 'name') %>  
  <%= f.input :part_num, :label => t('Part#'), :readonly => readonly?(@bom, 'part_num') %>
  <%= f.input :spec, :label => t('Spec'), :input_html => {:rows => 3}, :readonly => readonly?(@bom, 'spec') %>
  <%= f.input :qty, :label => t('Qty'), :readonly => readonly?(@bom, 'qty') %>
  <%= f.input :unit, :label => t('Qty Unit'), :collection => @qty_unit, :readonly => readonly?(@bom, 'unit') %>
  <%= f.input :order_date, :label => t('Order Date'), :as => :string, :readonly => readonly?(@bom, 'order_date') %>
  <%= f.input :received, :label => t("Received?"), :as => :boolean unless readonly?(@bom, 'received') %>
  <%= f.input :received_noupdate, :label => t("Received?"), :readonly => true, :input_html => {:value => @bom.received ? t('Yes') : t('No') } if readonly?(@bom, 'received') %>
  <%= f.input :status_id, :label => t('BOM Status'), :collection => Commonx::MiscDefinition.where(:for_which => 'bom_status') unless readonly?(@bom, 'status_id') %>
  <%= f.input :status_id, :label => t('BOM Status'), :readonly => true, :input_html => {:value => @bom.status.name} if readonly?(@bom, 'status_id') %>
  <%= f.input :supplier_id, :label => t('Supplier'), :collection => BillOfMaterialx.supplier_class.where(:active => true).order('id') unless readonly?(@bom, 'supplier_id') %>
  <%= f.input :supplier_name, :label => t('Supplier'),  :readonly => true, :input_html => {:value => @bom.supplier.name} if @bom.supplier_id.present? && readonly?(@bom, 'supplier_id') %>
  <%= f.input :manufacturer_id, :label => t('Manufacturer'), :collection => BillOfMaterialx.manufacturer_class.where(:active => true).order('id') unless readonly?(@bom, 'manufacturer_id') %>
  <%= f.input :manufacturer_name, :label => t('Manufacturer'), :readonly => true, :input_html => {:value => @bom.manufacturer.name} if @bom.manufacturer_id.present? && readonly?(@bom, 'manufacturer_id') %>  
  <%= f.input :receiving_date, :label => t('Receiving Date'), :as => :string %>
  <%= f.input :actual_receiving_date, :label => t("Actual Receiving Date"), :as => :string %> 
  <%= f.input :void_noupdate, :label => t('Void'), :readonly => true, :required => false, :input_html => {:value => @bom.void} if readonly?(@bom, 'void') %>
  <%= f.input :void, :label => t('Void'), :input_html => {:value => @bom.void} unless readonly?(@bom, 'void') %>
  <%= f.input :brief_note, :label => t('Brief Note'), :readonly => readonly?(@bom, 'brief_note'), :input_html => {:rows => 2} %>
    
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/bill_of_materialx/boms/_form_list.html.erb
 <% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
  <h4><%=@title %></h>
<div class="pagination"><%= will_paginate models %></div>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Project Name') %></th>
			<th><%= t('Customer') %></th>
			<th><%= t('Part Name') %></th>
			<th><%= t('Part#') %></th>
			<th><%= t('Spec') %></th>
			<th><%= t('Qty/Unit') %></th>
			<th><%= t('Order Date') %></th>
			<th><%= t('Supplier') %></th>
			<th><%= t('Manufacturer') %></th>
			<th><%= t('Receiving Date') %></th>
			<th><%= t('Received') %></th>
			<th><%= t('Last Updated By') %></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<% unless has_action_right?('show', params[:controller], r) %>
		  	  <td><%= prt(r, :id) %></td>
		  	<% else %>
		  	  <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{bom_path(r)}" %></td>
		  	<% end %>
		  	<% unless has_action_right?('show', BillOfMaterialx.project_class.to_s.underscore.pluralize) %>
		  	  <td><%= prt(r, 'project.name') %></td>
		  	<% else %>
		  	  <td><%= link_to r.project.name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(BillOfMaterialx.show_project_path))}" %></td>
		  	<% end %>
		  	<% unless has_action_right?('show', BillOfMaterialx.customer_class.to_s.underscore.pluralize) %>
		  	  <td><%= BillOfMaterialx.customer_class.find_by_id(BillOfMaterialx.project_class.find_by_id(r.project_id).customer_id).name %></td>
		  	<% else %>
		  	  <td><%= link_to r.customer.short_name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(BillOfMaterialx.show_customer_path))}" %></td>
		  	<% end %>
		  	<td><%= prt(r, :name) %></td>
			<td><%= prt(r, :part_num) %></td>
			<td><%= prt(r, :spec) %></td>
			<td><%= prt(r, :qty) %>/<%= prt(r, :unit) %></td>
			<td><%= r.order_date.strftime("%Y/%m/%d") if r.order_date.present? %></td>
			<% unless has_action_right?('show', BillOfMaterialx.supplier_class.to_s.underscore.pluralize) %>
		  	  <td><%= prt(r, 'supplier.short_name') if r.supplier_id.present? %></td>
		  	<% else %>
		  	  <td><%= link_to r.supplier.short_name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(BillOfMaterialx.show_supplier_path))}" if r.supplier_id.present? %></td>
		  	<% end %>
		    <td><%= prt(r, 'manufacturer.short_name') if r.manufacturer_id.present? %></td>
		  	<td><%= r.receiving_date.strftime("%Y/%m/%d") if r.receiving_date.present? %></td>
			<td><%= r.received ? t('Yes') : t('No') %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td> 
			<td><%= link_to t('Quote Tasks'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(event_taskx.event_tasks_path(task_category: 't_category'))}", :class => BUTTONS_CLS['action']   %></td>
			<td><%= link_to t('Quotes'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(in_quotex.quotes_path)}", :class => BUTTONS_CLS['action']   %> </td>
			<td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_bom_path(r, :parent_record_id => r.project_id, :parent_resource => BillOfMaterialx.project_class.to_s.underscore.pluralize)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	
	    </th>
	  </tr>
	</table>
	
	<% end %>
	

app/views/bill_of_materialx/boms/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
  <h4><%=@title %></h4>
<%= simple_form_for @bom do |f| %>  
      <%= f.input :customer_name, :label => t('Customer'), :readonly => true, :input_html => {:value => @customer.name} %>
      <%= f.input :project_name, :label => t('Project Name'), :readonly => true, :input_html => {:value => @project.name} %>
	  <%= f.input :project_id, :as => :hidden, :input_html => {:value => @project.id} %>
	  <%= f.input :name, :label => t('Part Name') %>  
	  <%= f.input :part_num, :label => t('Part#') %>
	  <%= f.input :spec, :label => t('Spec'), :input_html => {:rows => 3} %>
	  <%= f.input :qty, :label => t('Qty') %>
	  <%= f.input :unit, :label => t('Qty Unit'), :collection => @qty_unit, :include_blank => true %>
	  <%= f.input :order_date, :label => t('Order Date'), :as => :string %>
      <%= f.input :received, :label => t("Received?"), :as => :boolean %>
	  <%= f.input :status_id, :label => t('BOM Status'), :collection => Commonx::MiscDefinition.where(:for_which => 'bom_status'), :include_blank => true %>
	  <%= f.input :supplier_id, :label => t('Supplier'), :collection => BillOfMaterialx.supplier_class.where(:active => true).order('id') %>
	  <%= f.input :manufacturer_id, :label => t('Manufacturer'), :collection => BillOfMaterialx.manufacturer_class.where(:active => true).order('id') %>
	  <%= f.input :receiving_date, :label => t('Receiving Date'), :as => :string %>
	  <%= f.input :brief_note, :label => t('Brief Note'), :input_html => {:rows => 2} %>
	  
	  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
	  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>
  
<% end%>

app/views/bill_of_materialx/boms/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/bill_of_materialx/boms/edit.html.erb
<div id="main_body">
 
<%= render 'form'  %>
 
</div>
  
 

app/views/bill_of_materialx/boms/index.html.erb
<div id="main_body">
	
	<%= render partial: 'form_list', locals: {models: @boms} %>
 
</div>

app/views/bill_of_materialx/boms/new.html.erb
<div id="main_body">

<%= render 'form_new' %>

</div>

app/views/bill_of_materialx/boms/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div id="main_body">
<h4><%=@title %></h4>

<p>
  <b><%= t('Project Name') %></b>
  <%= @bom.project.name %>
</p>
<p>
  <b><%= t('Name') %></b>
  <%= @bom.name %>
</p>
<p>
  <b><%= t('Part#') %></b>
  <%= @bom.part_num %>
</p>
<p>
  <b><%= t('Spec') %></b>
  <%= @bom.spec %>
</p>
<p>
  <b><%= t('Qty/Unit') %></b>
  <%= @bom.qty %>/<%=@bom.unit %>
</p>
<p>
  <b><%= t('Purchasing Status') %></b>
  <%= @bom.status.name if @bom.status_id.present? %>
</p>
<p>
  <b><%= t('Supplier') %></b>
  <%= @bom.supplier.name if @bom.supplier_id.present? %>
</p>
<p>
  <b><%= t('Manufacturer') %></b>
  <%= @bom.manufacturer.name if @bom.manufacturer_id.present? %>
</p>
<p>
  <b><%= t('Order Date') %></b>
  <%= @bom.order_date.strftime('%Y/%m/%d') if @bom.order_date.present? %>
</p>
<p>
  <b><%= t('Receiving Date') %></b>
  <%= @bom.receiving_date.strftime('%Y/%m/%d') if @bom.receiving_date.present? %>
</p>
<p>
  <b><%= t('Acutal Receiving Date') %></b>
  <%= @bom.actual_receiving_date.strftime('%Y/%m/%d') if @bom.actual_receiving_date.present? %>
</p>
<p>
  <b><%= t('Received?') %></b>
  <%= @bom.received ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Void') %></b>
  <%= @bom.void ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @bom.last_updated_by.name %>
</p>
<p>
  <b>LOG：</b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @bom.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.last_updated_by.name %>,&nbsp; <%= t.log %> </li>
  <% end %>
</p>

	<table class="table table-striped">
	  <tr>
	    <th>
 		  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  		  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  	  <%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @bom.id, :resource_name => params[:controller], :subaction => 'bom', :format => :js), :remote => true, 
                          :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_bom', 'commonx/logs') %>
        </th>
	  </tr>
	</table>    	
</div>

<% end %>

app/views/bill_of_materialx/boms/update.html.erb
<h1>EventTasks#update</h1>
<p>Find me in app/views/event_taskx/event_tasks/update.html.erb</p>